version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: redis
    versions:
    - 3.1.2
  - dependency-name: socket.io
    versions:
    - 3.1.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: redis-commands
    versions:
    - 1.6.0
  - dependency-name: handlebars
    versions:
    - 4.7.6
