language: node_js
node_js:
  - "8"
env:
  - COMPOSE_VERSION=1.22.0
  - NODE_ENV=development

sudo: required
services:
  - docker

before_install:
  # Docker Compose Install
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  # Docker
  - docker-compose build
  - docker-compose up -d

before_script:
  # coveralls Install
  - npm install coveralls

script:
  - npm run lint
  - npm run test-unit

after_script:
  - docker-compose stop
  - docker-compose rm -f

after_success: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
