language: node_js
node_js:
  - "8"
env:
- NODE_ENV=development

before_script:
  npm install coveralls

script:
  - npm run test-unit

after_success: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js