FROM nginx
MAINTAINER akabakibi

ENV SERVICE_NAME iparkmini
ENV SERVICE_80_TAGS http

# Consul health checks
ENV SERVICE_80_CHECK_HTTP=/version.txt
ENV SERVICE_80_CHECK_INTERVAL=60s
ENV SERVICE_80_CHECK_TIMEOUT=3s
